"""Language management for UI and pipeline."""

from enum import Enum


class Language(Enum):
    """Supported languages."""

    FRENCH = "fr"
    ENGLISH = "en"
    ARABIC = "ar"


class LanguageManager:
    """Manages UI translations and language settings."""

    # UI Translations
    TRANSLATIONS = {
        "fr": {
            # Application
            "app_title": "Hrisa Docs",
            # Tabs
            "tab_documents": "Documents",
            "tab_themes": "Thèmes",
            "tab_synthesis": "Synthèse",
            "tab_settings": "Paramètres",
            # Menu
            "menu_file": "Fichier",
            "menu_import": "Importer",
            "menu_open_file": "Ouvrir un fichier",
            "menu_import_url": "Importer depuis URL",
            "menu_search_import": "Rechercher et importer",
            "menu_exit": "Quitter",
            "menu_project": "Projet",
            "menu_new_project": "Nouveau projet",
            "menu_manage_projects": "Gérer les projets",
            "menu_project_settings": "Paramètres du projet",
            "menu_settings": "Paramètres",
            "menu_appearance": "Apparence",
            "menu_chunk_settings": "Paramètres de découpage",
            "menu_model_settings": "Paramètres du modèle",
            "menu_help": "Aide",
            "menu_about": "À propos",
            "appearance_restart_msg": "Les paramètres d'apparence ont été mis à jour. Certains changements peuvent nécessiter le redémarrage de l'application pour un effet complet.",
            # Appearance settings dialog
            "dialog_appearance_settings": "Paramètres d'apparence",
            "section_theme": "Thème",
            "section_size": "Taille et accessibilité",
            "label_theme": "Thème",
            "label_size_profile": "Profil de taille",
            "theme_dark": "Sombre",
            "theme_light": "Clair",
            "theme_dark_desc": "Le thème sombre réduit la fatigue oculaire dans les environnements peu éclairés et économise la batterie sur les écrans OLED.",
            "theme_light_desc": "Le thème clair offre un contraste élevé et est idéal pour les environnements bien éclairés.",
            "size_small": "Petit (Compact)",
            "size_medium": "Moyen (Confortable)",
            "size_large": "Grand (Accessible)",
            "size_small_desc": "Interface compacte avec des polices et des contrôles plus petits. Maximise l'espace à l'écran.",
            "size_medium_desc": "Interface équilibrée avec des tailles confortables. Recommandé pour la plupart des utilisateurs.",
            "size_large_desc": "Polices et contrôles plus grands pour une meilleure lisibilité. Idéal pour les besoins d'accessibilité ou les grands écrans.",
            "size_info": "Choisissez un profil de taille plus grand pour une meilleure lisibilité et accessibilité. Cela affecte les tailles de police, les dimensions des boutons et l'espacement dans toute l'application.",
            "appearance_info": "Les modifications seront appliquées immédiatement. Vous devrez peut-être redémarrer l'application pour que tous les changements prennent effet.",
            "settings_applied": "Paramètres appliqués",
            "settings_applied_msg": "Les paramètres d'apparence ont été appliqués. Certaines modifications peuvent nécessiter le redémarrage de l'application.",
            # Files tab
            "section_input_docs": "Documents source",
            "section_output_files": "Documents générés",
            "status_no_output_files": "Aucun fichier généré",
            "status_n_output_files": "{} fichier(s) généré(s)",
            "btn_refresh": "Actualiser",
            "btn_open": "Ouvrir",
            "btn_open_folder": "Ouvrir le dossier",
            "btn_delete": "Supprimer",
            "btn_delete_all": "Tout supprimer",
            "btn_cancel": "Annuler",
            "btn_duplicate": "Dupliquer",
            "tooltip_refresh_files": "Actualiser la liste des fichiers",
            "tooltip_open_file": "Ouvrir le fichier sélectionné",
            "tooltip_open_folder": "Ouvrir le dossier de sortie",
            "tooltip_delete_file": "Supprimer le fichier sélectionné",
            "tooltip_delete_all_outputs": "Supprimer tous les fichiers générés",
            "confirm_delete": "Confirmer la suppression",
            "confirm_delete_multiple": "Êtes-vous sûr de vouloir supprimer {0} fichiers sélectionnés ?",
            "confirm_delete_all": "Confirmer la suppression de tous",
            "confirm_delete_all_msg": "Êtes-vous sûr de vouloir supprimer TOUS les {0} fichiers générés ?",
            # Document tab
            "btn_add": "Ajouter",
            "btn_remove": "Retirer",
            "btn_clear_all": "Tout effacer",
            "btn_clear_database": "Réinitialiser",
            "btn_process": "Traiter les documents",
            "status_no_docs": "Aucun document chargé",
            "status_n_docs": "{} document(s) chargé(s)",
            "status_processing": "Traitement en cours...",
            "status_complete": "Traitement terminé : {} morceaux",
            "status_processing_failed": "Échec du traitement",
            "status_ready_local": "Prêt - Traitement 100% local (pas de cloud)",
            "status_added_docs": "{} document(s) ajouté(s)",
            "status_discovering_themes": "Découverte des thèmes en cours...",
            "status_theme_discovery_failed": "Échec de la découverte de thèmes",
            "status_generating_book": "Génération du livre en cours...",
            "status_synthesis_failed": "Échec de la génération du livre",
            "status_writing_chapter": "Écriture du chapitre {}/{}",
            "status_generating_outline": "Génération du plan du chapitre...",
            "status_synthesizing_content": "Synthèse du contenu...",
            "status_formatting_output": "Formatage de la sortie...",
            # Worker progress messages
            "worker_initializing": "Initialisation...",
            "worker_processing_doc": "Traitement de {}...",
            "worker_embedding_chunks": "Intégration de {} morceaux...",
            "worker_embedding_chunk": "Intégration du morceau {}/{}...",
            "worker_completed_stored": "Terminé ! {} morceaux stockés",
            "worker_retrieving_chunks": "Récupération des morceaux...",
            "worker_analyzing_chunks": "Analyse de {} morceaux...",
            "worker_clustering": "Regroupement des thèmes...",
            "worker_discovered_themes": "{} thèmes découverts",
            "worker_loading_themes": "Chargement des thèmes...",
            "worker_synthesizing_chapters": "Synthèse de {} chapitres...",
            "worker_generating_markdown": "Génération du Markdown...",
            "worker_generating_docx": "Génération du DOCX...",
            "worker_generating_pdf": "Génération du PDF (cela peut prendre une minute)...",
            "worker_synthesis_complete": "Synthèse terminée !",
            # Tooltips - Documents
            "tooltip_add_docs": "Ajouter des documents PDF",
            "tooltip_remove_doc": "Retirer le document sélectionné",
            "tooltip_clear_all": "Retirer tous les documents",
            "tooltip_clear_database": "Réinitialiser complètement la base de données vectorielle",
            "tooltip_process_docs": "Extraire le texte, découper et intégrer les documents",
            "tooltip_discover_themes": "Analyser les documents et découvrir les thèmes",
            # Theme tab
            "btn_discover_themes": "Découvrir les thèmes",
            "btn_rename": "Renommer",
            "btn_merge": "Fusionner",
            "label_discovered_themes": "Thèmes découverts",
            "label_chunks": "morceaux",
            "status_no_themes": "Aucun thème découvert",
            "status_n_themes": "{} thème(s) découvert(s)",
            "theme_discovery_complete": "Découverte de thèmes terminée : {} thèmes",
            # Tooltips - Themes
            "tooltip_rename_theme": "Renommer le thème sélectionné",
            "tooltip_merge_themes": "Fusionner les thèmes sélectionnés",
            "tooltip_delete_theme": "Supprimer le thème sélectionné",
            # Synthesis tab
            "label_synthesis_config": "Configuration de synthèse",
            "label_theme_discovery": "Découverte de thèmes",
            "label_num_themes": "Nombre de thèmes :",
            "label_auto_detect": "Détecter automatiquement le nombre optimal",
            "label_synthesis_settings": "Paramètres de synthèse",
            "label_synthesis_level": "Niveau de synthèse :",
            "label_chunks_per_chapter": "Densité de synthèse :",
            "label_output_settings": "Paramètres de sortie",
            "label_output_format": "Format de sortie :",
            "label_include_citations": "Inclure les citations sources",
            "btn_start_synthesis": "🚀 Démarrer la synthèse",
            "status_ready": "Prêt pour la synthèse",
            "status_configure": "Configurez les paramètres et traitez les documents pour commencer",
            "synthesis_complete": "Synthèse terminée !",
            # Tooltips - Synthesis
            "tooltip_num_themes": "Nombre de thèmes à découvrir",
            "tooltip_auto_detect": "Déterminer automatiquement le nombre optimal de thèmes",
            "tooltip_synthesis_level": "Longueur de sortie par rapport aux documents sources",
            "tooltip_chunks_per_chapter": "Contrôle la densité de la synthèse : plus de morceaux = plus détaillé, moins = plus condensé (50-300 recommandé)",
            "tooltip_output_format": "Format de sortie pour le livre généré (PDF nécessite pandoc + MacTeX)",
            "tooltip_include_citations": "Ajouter des citations aux documents sources",
            "tooltip_start_synthesis": "Démarrer la synthèse du livre",
            # Settings tab
            "label_language": "Langue :",
            "label_language_ui": "Langue de l'interface :",
            "label_language_pipeline": "Langue du pipeline :",
            "label_ollama_model": "Modèle Ollama :",
            "label_vector_store": "Base vectorielle :",
            "label_output_dir": "Répertoire de sortie :",
            # Synthesis levels
            "synthesis_short": "Court (15%)",
            "synthesis_normal": "Normal (30%)",
            "synthesis_comprehensive": "Complet (50%)",
            # Output formats
            "format_markdown": "Markdown",
            "format_docx": "DOCX",
            "format_pdf": "PDF",
            "format_both": "Markdown + DOCX",
            "format_all": "Tout (MD + DOCX + PDF)",
            # Dialogs
            "dialog_select_pdfs": "Sélectionner des documents",
            "dialog_pdf_filter": "Tous les documents (*.pdf *.txt *.docx);;Fichiers PDF (*.pdf);;Fichiers texte (*.txt);;Documents Word (*.docx)",
            "dialog_no_documents": "Aucun document",
            "dialog_no_documents_msg": "Veuillez d'abord ajouter des documents.",
            "dialog_processing_complete": "Traitement terminé",
            "dialog_processing_complete_msg": "Documents traités avec succès !\nTotal de morceaux : {}",
            "dialog_can_discover_themes": "Vous pouvez maintenant découvrir les thèmes.",
            "dialog_processing_error": "Erreur de traitement",
            "dialog_processing_error_msg": "Échec du traitement des documents :\n\n{}",
            "dialog_theme_discovery_complete": "Découverte de thèmes terminée",
            "dialog_theme_discovery_complete_msg": "Découvert {} thèmes !\nVous pouvez maintenant réviser et modifier les thèmes, puis générer votre livre.",
            "dialog_theme_discovery_error": "Erreur de découverte de thèmes",
            "dialog_theme_discovery_error_msg": "Échec de la découverte de thèmes :\n\n{}",
            "dialog_no_themes": "Aucun thème",
            "dialog_no_themes_msg": "Veuillez d'abord découvrir les thèmes avant de générer le livre.",
            "dialog_synthesis_complete": "Synthèse terminée",
            "dialog_synthesis_success": "Livre généré avec succès !",
            "dialog_synthesis_error": "Erreur de synthèse",
            "dialog_synthesis_error_msg": "Échec de la génération du livre :\n\n{}",
            "dialog_confirm_merge": "Confirmer la fusion",
            "dialog_confirm_merge_msg": "Attention : Les thèmes ont des tailles très différentes.\n\nThèmes à fusionner :\n{}\n\nUn thème est beaucoup plus grand que l'autre. Voulez-vous vraiment les fusionner ?",
            "dialog_rename_theme": "Renommer le thème",
            "dialog_rename_theme_msg": "Entrez le nouveau nom du thème :",
            "dialog_clear_database": "Réinitialiser la base de données",
            "dialog_clear_database_msg": "⚠️ Attention : Cette action supprimera TOUTES les données :\n\n• Tous les morceaux de documents\n• Tous les thèmes découverts\n• Tous les intégrations vectorielles\n\nCette action est IRRÉVERSIBLE.\n\nVoulez-vous vraiment continuer ?",
            "dialog_database_cleared": "Base de données réinitialisée",
            "dialog_database_cleared_msg": "La base de données a été complètement réinitialisée.",
            "dialog_about_title": "À propos du Processeur de Documents",
            "dialog_about_content": "<h2>Processeur de Documents</h2><p>Synthèse de documents basée sur RAG utilisant des LLMs locaux</p><p><b>Fonctionnalités :</b></p><ul><li>Traitement 100% local (respect de la vie privée)</li><li>Détection automatique de la langue</li><li>Découverte de thèmes par clustering</li><li>Export multi-format (MD, DOCX, PDF)</li></ul><p><b>Stack technique :</b> ChromaDB, Ollama, PyQt6</p>",
            # Project Dashboard
            "projects_dashboard": "Tableau de bord des projets",
            "current_project": "Projet actuel",
            "no_project": "Aucun projet",
            "btn_manage_projects": "Gérer les projets",
            "btn_project_settings": "Paramètres du projet",
            "msg_project_load_error": "Échec du chargement du projet",
            "msg_coming_soon": "Bientôt disponible !",
            "info": "Information",
            # Project Settings Dialog
            "dialog_project_settings": "Paramètres du projet",
            "section_project_info": "Informations du projet",
            "section_llm_settings": "Paramètres du modèle de langage",
            "section_processing_settings": "Paramètres de traitement",
            "section_output_settings": "Paramètres de sortie",
            "label_project_name": "Nom du projet",
            "label_author": "Auteur",
            "label_tags": "Étiquettes",
            "placeholder_tags": "Étiquettes séparées par des virgules",
            "label_project_language": "Langue du projet",
            "label_llm_model": "Modèle LLM",
            "label_temperature": "Température",
            "label_embedding_model": "Modèle d'embedding",
            "label_chunk_size": "Taille du bloc",
            "label_chunk_overlap": "Chevauchement des blocs",
            "label_output_format": "Format de sortie par défaut",
            "label_include_citations": "Inclure les citations",
            "label_citation_style": "Style de citation",
            "msg_settings_saved": "Paramètres du projet enregistrés avec succès",
            "btn_new_project": "Nouveau Projet",
            "btn_favorite": "Favori",
            "btn_unfavorite": "Retirer des favoris",
            "btn_archive": "Archiver",
            "btn_delete_permanent": "Supprimer définitivement",
            "placeholder_search": "Rechercher des projets...",
            "placeholder_project_name": "Entrez le nom du projet",
            "placeholder_description": "Description optionnelle",
            "filter_all": "Tous les projets",
            "filter_active": "Actifs",
            "filter_archived": "Archivés",
            "filter_favorites": "Favoris",
            "sort_updated": "Dernière modification",
            "sort_created": "Date de création",
            "sort_opened": "Dernière ouverture",
            "sort_name": "Nom",
            "label_name": "Nom",
            "label_description": "Description",
            "label_template": "Modèle",
            "label_mark_favorite": "Marquer comme favori",
            "template_default": "Par défaut",
            "template_academic": "Recherche académique",
            "template_legal": "Analyse juridique",
            "template_creative": "Écriture créative",
            "template_technical": "Documentation technique",
            "dialog_new_project": "Nouveau Projet",
            "dialog_delete_project": "Supprimer le projet",
            "msg_project_name_required": "Le nom du projet est requis",
            # Figure Extraction / Data Update
            "tab_data_update": "Mise à jour des données",
            "figure_extraction_title": "Extraction de figures et statistiques",
            "figure_extraction_control": "Contrôle d'extraction",
            "btn_extract_figures": "Extraire les figures du document",
            "figure_statistics": "Statistiques d'extraction",
            "label_total": "Total",
            "label_currency": "Monnaie",
            "label_percentage": "Pourcentage",
            "label_dates": "Dates",
            "label_filter_type": "Filtrer par type :",
            "label_tables_only": "Tableaux uniquement",
            "filter_all": "Tous",
            "filter_currency": "Monnaie",
            "filter_percentage": "Pourcentage",
            "filter_date": "Date",
            "filter_range": "Plage",
            "filter_quantity": "Quantité",
            "filter_number": "Nombre",
            "btn_export_csv": "Exporter en CSV",
            "btn_update_figures": "Mettre à jour les figures sélectionnées...",
            "btn_clear_results": "Effacer les résultats",
            "tooltip_export_csv": "Exporter les résultats en fichier CSV",
            "tooltip_update_figures": "Rechercher des valeurs mises à jour en ligne",
            "status_no_document": "Aucun document chargé",
            "status_ready_extract": "Prêt à extraire de : {}",
            "status_ready_extract_count": "Prêt à extraire de {} {}",
            "word_document": "document",
            "word_documents": "documents",
            "status_extracting": "Extraction en cours...",
            "status_extraction_complete": "{} figures extraites avec succès en {:.2f}s",
            "status_extraction_error": "Erreur : {}",
            "status_results_cleared": "Résultats effacés",
            "status_showing_figures": "Affichage de {} sur {} figures",
            "dialog_no_data_export": "Aucune donnée",
            "dialog_no_data_export_msg": "Aucune figure à exporter. Veuillez d'abord extraire les figures.",
            "dialog_select_document": "Sélectionner le document pour l'extraction de figures",
            "dialog_document_filter": "Documents (*.pdf *.docx *.txt);;Tous les fichiers (*)",
            "dialog_export_csv": "Exporter les figures en CSV",
            "dialog_csv_filter": "Fichiers CSV (*.csv);;Tous les fichiers (*)",
            "dialog_export_success": "Exportation réussie",
            "dialog_export_success_msg": "Exporté {} figures vers :\n{}",
            "dialog_export_error": "Erreur d'exportation",
            "dialog_export_error_msg": "Échec de l'exportation CSV :\n{}",
            "dialog_no_selection": "Aucune sélection",
            "dialog_no_selection_msg": "Veuillez sélectionner au moins une figure à mettre à jour.",
            "dialog_update_figures_title": "Mise à jour des figures",
            "dialog_update_figures_msg": "{} figure(s) sélectionnée(s) :\n\n{}\n\nCette fonctionnalité recherchera des valeurs mises à jour en ligne pour les figures sélectionnées.\n\nNote : Cette fonctionnalité est en cours de développement.",
            "and_more": "et {} de plus",
            "table_header_select": "Sélection",
            "table_header_type": "Type",
            "table_header_value": "Valeur",
            "table_header_numeric": "Numérique",
            "table_header_unit_currency": "Unité/Monnaie",
            "table_header_year": "Année",
            "table_header_location": "Emplacement",
            "table_header_context": "Contexte",
            "location_table": "Tableau",
            "location_page": "Page",
            "location_para": "Par.",
            "figure_type_currency": "Monnaie",
            "figure_type_percentage": "Pourcentage",
            "figure_type_date": "Date",
            "figure_type_range": "Plage",
            "figure_type_quantity": "Quantité",
            "figure_type_number": "Nombre",
            "csv_header_type": "Type",
            "csv_header_value": "Valeur",
            "csv_header_numeric_value": "Valeur numérique",
            "csv_header_unit_currency": "Unité/Monnaie",
            "csv_header_year": "Année",
            "csv_header_page": "Page",
            "csv_header_paragraph": "Paragraphe",
            "csv_header_is_from_table": "Provient d'un tableau",
            "csv_header_table_index": "Index du tableau",
            "csv_header_table_row": "Ligne du tableau",
            "csv_header_table_column": "Colonne du tableau",
            "csv_header_table_row_header": "En-tête de ligne",
            "csv_header_table_column_header": "En-tête de colonne",
            "csv_header_context_sentence": "Phrase de contexte",
            "csv_header_confidence_score": "Score de confiance",
            "csv_value_yes": "Oui",
            "csv_value_no": "Non",
            "msg_project_created": "Projet créé avec succès !",
            "msg_create_project_error": "Erreur lors de la création du projet",
            "msg_delete_archived_project": "Supprimer définitivement ce projet archivé ?",
            "msg_delete_active_project": "Archiver ou supprimer définitivement ce projet ?",
            "msg_project_deleted": "Projet supprimé définitivement",
            "msg_project_archived": "Projet archivé",
            "success": "Succès",
            # URL Import Dialog
            "dialog_url_import": "Importer depuis URL",
            "menu_import_url": "Importer depuis URL",
            "url_import_instructions": "Entrez les URLs à importer (une par ligne). Supporte PDF, pages HTML et fichiers texte.",
            "section_urls": "URLs",
            "label_quick_add": "Ajout rapide",
            "btn_import": "Importer",
            "label_timeout": "Délai d'expiration",
            "label_convert_html": "Convertir les pages HTML en texte",
            "label_verify_ssl": "Vérifier les certificats SSL",
            "section_progress": "Progression",
            "status_import_complete": "Importation terminée !",
            "status_import_failed": "Échec de l'importation",
            "warning_no_urls": "Veuillez entrer au moins une URL.",
            "error_import_failed": "Échec de l'importation",
            "summary_import_success": "{0} document(s) importé(s) avec succès.",
            "summary_import_partial": "{0} URL(s) ont échoué.",
            # Search & Import Dialog
            "dialog_search_import": "Rechercher et importer depuis les sources",
            "search_instructions": "Entrez des mots-clés pour rechercher dans les bases de données gouvernementales et légales. Les résultats seront affichés pour révision avant importation.",
            "search_query_label": "Requête de recherche",
            "search_settings_label": "Paramètres de recherche",
            "max_results_label": "Résultats max par requête",
            "google_api_key_label": "Clé API Google",
            "search_engine_id_label": "ID du moteur de recherche",
            "progress_label": "Progression",
            "results_label": "Résultats de recherche",
            "search_button": "Rechercher",
            "import_selected_button": "Importer les sélectionnés",
            "results_count": "{} résultats trouvés",
            "quick_add_placeholder": "Ajout rapide...",
            "add_button": "Ajouter",
            "clear_button": "Effacer",
            "no_queries_warning": "Veuillez entrer au moins une requête de recherche.",
            "api_key_required": "La clé API Google et l'ID du moteur de recherche sont requis.\n\nObtenez une clé API: https://console.cloud.google.com/\nCréez un moteur de recherche: https://programmablesearchengine.google.com/",
            "no_selection_warning": "Veuillez sélectionner au moins un résultat à importer.",
            "source_selection_label": "Sources (Optionnel)",
            "source_selection_info": "Sélectionnez des sources spécifiques pour la recherche native. Laissez non coché pour rechercher toutes les sources via Google.",
            "other_sources_label": "Les autres sources seront recherchées via l'API Google",
            "search_strategy_label": "Stratégie de recherche :",
            "api_key_required_conditional": "La clé API Google et l'ID du moteur de recherche sont requis pour cette stratégie de recherche.\n\nPour rechercher sans API Google, sélectionnez la stratégie 'Native uniquement' et cochez data.gov.tn.",
            # Phase 2d - Advanced Features
            "remember_credentials": "Se souvenir des identifiants (sécurisé)",
            "clear_credentials": "Effacer les identifiants sauvegardés",
            "confirm_clear_credentials": "Êtes-vous sûr de vouloir effacer les identifiants sauvegardés ?",
            "credentials_cleared": "Identifiants effacés avec succès",
            "recent_searches": "Recherches récentes :",
            "clear_history": "Effacer l'historique",
            "confirm_clear_history": "Êtes-vous sûr de vouloir effacer l'historique de recherche ?",
            "history_cleared": "Historique effacé",
            "remove_from_history": "Supprimer",
            # Common
            "ok": "OK",
            "cancel": "Annuler",
            "yes": "Oui",
            "no": "Non",
            "error": "Erreur",
            "warning": "Avertissement",
        },
        "en": {
            # Application
            "app_title": "Hrisa Docs",
            # Tabs
            "tab_documents": "Documents",
            "tab_themes": "Themes",
            "tab_synthesis": "Synthesis",
            "tab_settings": "Settings",
            # Menu
            "menu_file": "File",
            "menu_import": "Import",
            "menu_open_file": "Open File",
            "menu_import_url": "Import from URL",
            "menu_search_import": "Search & Import",
            "menu_exit": "Exit",
            "menu_project": "Project",
            "menu_new_project": "New Project",
            "menu_manage_projects": "Manage Projects",
            "menu_project_settings": "Project Settings",
            "menu_settings": "Settings",
            "menu_appearance": "Appearance",
            "menu_chunk_settings": "Chunk Settings",
            "menu_model_settings": "Model Settings",
            "menu_help": "Help",
            "menu_about": "About",
            "appearance_restart_msg": "Appearance settings have been updated. Some changes may require restarting the application for full effect.",
            # Appearance settings dialog
            "dialog_appearance_settings": "Appearance Settings",
            "section_theme": "Theme",
            "section_size": "Size & Accessibility",
            "label_theme": "Theme",
            "label_size_profile": "Size Profile",
            "theme_dark": "Dark",
            "theme_light": "Light",
            "theme_dark_desc": "Dark theme reduces eye strain in low-light environments and saves battery on OLED screens.",
            "theme_light_desc": "Light theme provides high contrast and is ideal for well-lit environments.",
            "size_small": "Small (Compact)",
            "size_medium": "Medium (Comfortable)",
            "size_large": "Large (Accessible)",
            "size_small_desc": "Compact interface with smaller fonts and controls. Maximizes screen space.",
            "size_medium_desc": "Balanced interface with comfortable sizes. Recommended for most users.",
            "size_large_desc": "Larger fonts and controls for improved readability. Ideal for accessibility needs or larger displays.",
            "size_info": "Choose a larger size profile for better readability and accessibility. This affects font sizes, button dimensions, and spacing throughout the application.",
            "appearance_info": "Changes will be applied immediately. You may need to restart the application for all changes to take effect.",
            "settings_applied": "Settings Applied",
            "settings_applied_msg": "Appearance settings have been applied. Some changes may require restarting the application.",
            # Files tab
            "section_input_docs": "Source Documents",
            "section_output_files": "Generated Files",
            "status_no_output_files": "No generated files",
            "status_n_output_files": "{} generated file(s)",
            "btn_refresh": "Refresh",
            "btn_open": "Open",
            "btn_open_folder": "Open Folder",
            "btn_delete": "Delete",
            "btn_delete_all": "Delete All",
            "btn_cancel": "Cancel",
            "btn_duplicate": "Duplicate",
            "tooltip_refresh_files": "Refresh files list",
            "tooltip_open_file": "Open selected file",
            "tooltip_open_folder": "Open output folder",
            "tooltip_delete_file": "Delete selected file",
            "tooltip_delete_all_outputs": "Delete all generated files",
            "confirm_delete": "Confirm Delete",
            "confirm_delete_multiple": "Are you sure you want to delete {0} selected files?",
            "confirm_delete_all": "Confirm Delete All",
            "confirm_delete_all_msg": "Are you sure you want to delete ALL {0} generated files?",
            # Document tab
            "btn_add": "Add",
            "btn_remove": "Remove",
            "btn_clear_all": "Clear All",
            "btn_clear_database": "Reset DB",
            "btn_process": "Process Documents",
            "status_no_docs": "No documents loaded",
            "status_n_docs": "{} document(s) loaded",
            "status_processing": "Processing...",
            "status_complete": "Processing complete: {} chunks",
            "status_processing_failed": "Processing failed",
            "status_ready_local": "Ready - 100% local processing (no cloud)",
            "status_added_docs": "Added {} document(s)",
            "status_discovering_themes": "Discovering themes...",
            "status_theme_discovery_failed": "Theme discovery failed",
            "status_generating_book": "Generating book...",
            "status_synthesis_failed": "Book generation failed",
            "status_writing_chapter": "Writing chapter {}/{}",
            "status_generating_outline": "Generating chapter outline...",
            "status_synthesizing_content": "Synthesizing content...",
            "status_formatting_output": "Formatting output...",
            # Worker progress messages
            "worker_initializing": "Initializing...",
            "worker_processing_doc": "Processing {}...",
            "worker_embedding_chunks": "Embedding {} chunks...",
            "worker_embedding_chunk": "Embedding chunk {}/{}...",
            "worker_completed_stored": "Completed! Stored {} chunks",
            "worker_retrieving_chunks": "Retrieving chunks...",
            "worker_analyzing_chunks": "Analyzing {} chunks...",
            "worker_clustering": "Clustering themes...",
            "worker_discovered_themes": "Discovered {} themes",
            "worker_loading_themes": "Loading themes...",
            "worker_synthesizing_chapters": "Synthesizing {} chapters...",
            "worker_generating_markdown": "Generating Markdown...",
            "worker_generating_docx": "Generating DOCX...",
            "worker_generating_pdf": "Generating PDF (this may take a minute)...",
            "worker_synthesis_complete": "Synthesis complete!",
            # Tooltips - Documents
            "tooltip_add_docs": "Add PDF documents",
            "tooltip_remove_doc": "Remove selected document",
            "tooltip_clear_all": "Remove all documents",
            "tooltip_clear_database": "Completely reset the vector database",
            "tooltip_process_docs": "Extract text, chunk, and embed documents",
            "tooltip_discover_themes": "Analyze documents and discover themes",
            # Theme tab
            "btn_discover_themes": "Discover Themes",
            "btn_rename": "Rename",
            "btn_merge": "Merge",
            "btn_delete": "Delete",
            "label_discovered_themes": "Discovered Themes",
            "label_chunks": "chunks",
            "status_no_themes": "No themes discovered yet",
            "status_n_themes": "{} theme(s) discovered",
            "theme_discovery_complete": "Theme discovery complete: {} themes",
            # Tooltips - Themes
            "tooltip_rename_theme": "Rename selected theme",
            "tooltip_merge_themes": "Merge selected themes",
            "tooltip_delete_theme": "Delete selected theme",
            # Synthesis tab
            "label_synthesis_config": "Synthesis Configuration",
            "label_theme_discovery": "Theme Discovery",
            "label_num_themes": "Number of themes:",
            "label_auto_detect": "Auto-detect optimal number",
            "label_synthesis_settings": "Synthesis Settings",
            "label_synthesis_level": "Synthesis level:",
            "label_chunks_per_chapter": "Synthesis density:",
            "label_output_settings": "Output Settings",
            "label_output_format": "Output format:",
            "label_include_citations": "Include source citations",
            "btn_start_synthesis": "🚀 Start Synthesis",
            "status_ready": "Ready to synthesize",
            "status_configure": "Configure settings and process documents to begin",
            "synthesis_complete": "Synthesis complete!",
            # Tooltips - Synthesis
            "tooltip_num_themes": "Number of themes to discover",
            "tooltip_auto_detect": "Automatically determine optimal theme count",
            "tooltip_synthesis_level": "Output length relative to source documents",
            "tooltip_chunks_per_chapter": "Controls synthesis density: more chunks = more detailed, fewer = more condensed (50-300 recommended)",
            "tooltip_output_format": "Output format for generated book (PDF requires pandoc + MacTeX)",
            "tooltip_include_citations": "Add citations to source documents",
            "tooltip_start_synthesis": "Start book synthesis",
            # Settings tab
            "label_language": "Language:",
            "label_language_ui": "Interface language:",
            "label_language_pipeline": "Pipeline language:",
            "label_ollama_model": "Ollama model:",
            "label_vector_store": "Vector store:",
            "label_output_dir": "Output directory:",
            # Synthesis levels
            "synthesis_short": "Short (15%)",
            "synthesis_normal": "Normal (30%)",
            "synthesis_comprehensive": "Comprehensive (50%)",
            # Output formats
            "format_markdown": "Markdown",
            "format_docx": "DOCX",
            "format_pdf": "PDF",
            "format_both": "Markdown + DOCX",
            "format_all": "All (MD + DOCX + PDF)",
            # Dialogs
            "dialog_select_pdfs": "Select Documents",
            "dialog_pdf_filter": "All Documents (*.pdf *.txt *.docx);;PDF Files (*.pdf);;Text Files (*.txt);;Word Documents (*.docx)",
            "dialog_no_documents": "No Documents",
            "dialog_no_documents_msg": "Please add some documents first.",
            "dialog_processing_complete": "Processing Complete",
            "dialog_processing_complete_msg": "Successfully processed documents!\nTotal chunks: {}",
            "dialog_can_discover_themes": "You can now discover themes.",
            "dialog_processing_error": "Processing Error",
            "dialog_processing_error_msg": "Failed to process documents:\n\n{}",
            "dialog_theme_discovery_complete": "Theme Discovery Complete",
            "dialog_theme_discovery_complete_msg": "Discovered {} themes!\nYou can now review and edit themes, then generate your book.",
            "dialog_theme_discovery_error": "Theme Discovery Error",
            "dialog_theme_discovery_error_msg": "Failed to discover themes:\n\n{}",
            "dialog_no_themes": "No Themes",
            "dialog_no_themes_msg": "Please discover themes first before generating the book.",
            "dialog_synthesis_complete": "Synthesis Complete",
            "dialog_synthesis_success": "Book generated successfully!",
            "dialog_synthesis_error": "Synthesis Error",
            "dialog_synthesis_error_msg": "Failed to generate book:\n\n{}",
            "dialog_confirm_merge": "Confirm Merge",
            "dialog_confirm_merge_msg": "Warning: Themes have very different sizes.\n\nThemes to merge:\n{}\n\nOne theme is much larger than the other(s). Are you sure you want to merge them?",
            "dialog_rename_theme": "Rename Theme",
            "dialog_rename_theme_msg": "Enter new theme name:",
            "dialog_clear_database": "Reset Database",
            "dialog_clear_database_msg": "⚠️ Warning: This action will delete ALL data:\n\n• All document chunks\n• All discovered themes\n• All vector embeddings\n\nThis action is IRREVERSIBLE.\n\nDo you want to continue?",
            "dialog_database_cleared": "Database Reset",
            "dialog_database_cleared_msg": "The database has been completely reset.",
            "dialog_about_title": "About Hrisa Docs",
            "dialog_about_content": "<h2>Hrisa Docs</h2><p>RAG-based document synthesis using local LLMs</p><p><b>Features:</b></p><ul><li>100% local processing (privacy-first)</li><li>Automatic language detection</li><li>Theme discovery via clustering</li><li>Multi-format export (MD, DOCX, PDF)</li></ul><p><b>Tech Stack:</b> ChromaDB, Ollama, PyQt6</p>",
            # Project Dashboard
            "projects_dashboard": "Projects Dashboard",
            "current_project": "Current Project",
            "no_project": "No Project",
            "btn_manage_projects": "Manage Projects",
            "btn_project_settings": "Project Settings",
            "msg_project_load_error": "Failed to load project",
            "msg_coming_soon": "Coming soon!",
            "info": "Information",
            # Project Settings Dialog
            "dialog_project_settings": "Project Settings",
            "section_project_info": "Project Information",
            "section_llm_settings": "Language Model Settings",
            "section_processing_settings": "Processing Settings",
            "section_output_settings": "Output Settings",
            "label_project_name": "Project Name",
            "label_author": "Author",
            "label_tags": "Tags",
            "placeholder_tags": "Comma-separated tags",
            "label_language": "Language",
            "label_llm_model": "LLM Model",
            "label_temperature": "Temperature",
            "label_embedding_model": "Embedding Model",
            "label_chunk_size": "Chunk Size",
            "label_chunk_overlap": "Chunk Overlap",
            "label_output_format": "Default Output Format",
            "label_include_citations": "Include Citations",
            "label_citation_style": "Citation Style",
            "msg_settings_saved": "Project settings saved successfully",
            "btn_new_project": "New Project",
            "btn_favorite": "Favorite",
            "btn_unfavorite": "Unfavorite",
            "btn_archive": "Archive",
            "btn_delete_permanent": "Delete Permanently",
            "placeholder_search": "Search projects...",
            "placeholder_project_name": "Enter project name",
            "placeholder_description": "Optional description",
            "filter_all": "All Projects",
            "filter_active": "Active",
            "filter_archived": "Archived",
            "filter_favorites": "Favorites",
            "sort_updated": "Last Modified",
            "sort_created": "Date Created",
            "sort_opened": "Last Opened",
            "sort_name": "Name",
            "label_name": "Name",
            "label_description": "Description",
            "label_template": "Template",
            "label_mark_favorite": "Mark as favorite",
            "template_default": "Default",
            "template_academic": "Academic Research",
            "template_legal": "Legal Analysis",
            "template_creative": "Creative Writing",
            "template_technical": "Technical Documentation",
            "dialog_new_project": "New Project",
            "dialog_delete_project": "Delete Project",
            "msg_project_name_required": "Project name is required",
            "msg_project_created": "Project created successfully!",
            "msg_create_project_error": "Error creating project",
            "msg_delete_archived_project": "Permanently delete this archived project?",
            "msg_delete_active_project": "Archive or permanently delete this project?",
            "msg_project_deleted": "Project deleted permanently",
            "msg_project_archived": "Project archived",
            "success": "Success",
            # Figure Extraction / Data Update
            "tab_data_update": "Data Update",
            "figure_extraction_title": "Figure & Statistic Extraction",
            "figure_extraction_control": "Extraction Control",
            "btn_extract_figures": "Extract Figures from Document",
            "figure_statistics": "Extraction Statistics",
            "label_total": "Total",
            "label_currency": "Currency",
            "label_percentage": "Percentage",
            "label_dates": "Dates",
            "label_filter_type": "Filter by type:",
            "label_tables_only": "Tables only",
            "filter_all": "All",
            "filter_currency": "Currency",
            "filter_percentage": "Percentage",
            "filter_date": "Date",
            "filter_range": "Range",
            "filter_quantity": "Quantity",
            "filter_number": "Number",
            "btn_export_csv": "Export to CSV",
            "btn_update_figures": "Update Selected Figures...",
            "btn_clear_results": "Clear Results",
            "tooltip_export_csv": "Export results to CSV file",
            "tooltip_update_figures": "Search for updated values online",
            "status_no_document": "No document loaded",
            "status_ready_extract": "Ready to extract from: {}",
            "status_ready_extract_count": "Ready to extract from {} {}",
            "word_document": "document",
            "word_documents": "documents",
            "status_extracting": "Extracting...",
            "status_extraction_complete": "Successfully extracted {} figures in {:.2f}s",
            "status_extraction_error": "Error: {}",
            "status_results_cleared": "Results cleared",
            "status_showing_figures": "Showing {} of {} figures",
            "dialog_no_data_export": "No Data",
            "dialog_no_data_export_msg": "No figures to export. Please extract figures first.",
            "dialog_select_document": "Select Document for Figure Extraction",
            "dialog_document_filter": "Documents (*.pdf *.docx *.txt);;All Files (*)",
            "dialog_export_csv": "Export Figures to CSV",
            "dialog_csv_filter": "CSV Files (*.csv);;All Files (*)",
            "dialog_export_success": "Export Successful",
            "dialog_export_success_msg": "Exported {} figures to:\n{}",
            "dialog_export_error": "Export Error",
            "dialog_export_error_msg": "Failed to export CSV:\n{}",
            "dialog_no_selection": "No Selection",
            "dialog_no_selection_msg": "Please select at least one figure to update.",
            "dialog_update_figures_title": "Update Figures",
            "dialog_update_figures_msg": "{} figure(s) selected:\n\n{}\n\nThis feature will search for updated values online for the selected figures.\n\nNote: This feature is currently under development.",
            "and_more": "and {} more",
            "table_header_select": "Select",
            "table_header_type": "Type",
            "table_header_value": "Value",
            "table_header_numeric": "Numeric",
            "table_header_unit_currency": "Unit/Currency",
            "table_header_year": "Year",
            "table_header_location": "Location",
            "table_header_context": "Context",
            "location_table": "Table",
            "location_page": "Page",
            "location_para": "Para",
            "figure_type_currency": "Currency",
            "figure_type_percentage": "Percentage",
            "figure_type_date": "Date",
            "figure_type_range": "Range",
            "figure_type_quantity": "Quantity",
            "figure_type_number": "Number",
            "csv_header_type": "Type",
            "csv_header_value": "Value",
            "csv_header_numeric_value": "Numeric Value",
            "csv_header_unit_currency": "Unit/Currency",
            "csv_header_year": "Year",
            "csv_header_page": "Page",
            "csv_header_paragraph": "Paragraph",
            "csv_header_is_from_table": "Is From Table",
            "csv_header_table_index": "Table Index",
            "csv_header_table_row": "Table Row",
            "csv_header_table_column": "Table Column",
            "csv_header_table_row_header": "Table Row Header",
            "csv_header_table_column_header": "Table Column Header",
            "csv_header_context_sentence": "Context Sentence",
            "csv_header_confidence_score": "Confidence Score",
            "csv_value_yes": "Yes",
            "csv_value_no": "No",
            # URL Import Dialog
            "dialog_url_import": "Import from URL",
            "menu_import_url": "Import from URL",
            "url_import_instructions": "Enter URLs to import (one per line). Supports PDF, HTML pages, and text files.",
            "section_urls": "URLs",
            "label_quick_add": "Quick add",
            "btn_import": "Import",
            "label_timeout": "Timeout",
            "label_convert_html": "Convert HTML pages to text",
            "label_verify_ssl": "Verify SSL certificates",
            "section_progress": "Progress",
            "status_import_complete": "Import complete!",
            "status_import_failed": "Import failed",
            "warning_no_urls": "Please enter at least one URL.",
            "error_import_failed": "Import failed",
            "summary_import_success": "Successfully imported {0} document(s).",
            "summary_import_partial": "{0} URL(s) failed.",
            # Search & Import Dialog
            "dialog_search_import": "Search & Import from Research Sources",
            "search_instructions": "Enter keywords to search government and legal databases. Results will be displayed for review before importing.",
            "search_query_label": "Search Query",
            "search_settings_label": "Search Settings",
            "max_results_label": "Max results per query",
            "google_api_key_label": "Google API Key",
            "search_engine_id_label": "Search Engine ID",
            "progress_label": "Progress",
            "results_label": "Search Results",
            "search_button": "Search",
            "import_selected_button": "Import Selected",
            "results_count": "Found {} results",
            "quick_add_placeholder": "Quick add...",
            "add_button": "Add",
            "clear_button": "Clear",
            "no_queries_warning": "Please enter at least one search query.",
            "api_key_required": "Google API Key and Search Engine ID are required.\n\nGet an API key: https://console.cloud.google.com/\nCreate search engine: https://programmablesearchengine.google.com/",
            "no_selection_warning": "Please select at least one result to import.",
            "source_selection_label": "Sources (Optional)",
            "source_selection_info": "Select specific sources for native search. Leave unchecked to search all sources via Google.",
            "other_sources_label": "Other sources will be searched via Google API",
            "search_strategy_label": "Search Strategy:",
            "api_key_required_conditional": "Google API Key and Search Engine ID are required for this search strategy.\n\nTo search without Google API, select 'Native Only' strategy and check data.gov.tn.",
            # Phase 2d - Advanced Features
            "remember_credentials": "Remember credentials (secure)",
            "clear_credentials": "Clear Saved Credentials",
            "confirm_clear_credentials": "Are you sure you want to clear saved credentials?",
            "credentials_cleared": "Credentials cleared successfully",
            "recent_searches": "Recent Searches:",
            "clear_history": "Clear History",
            "confirm_clear_history": "Are you sure you want to clear search history?",
            "history_cleared": "History cleared",
            "remove_from_history": "Remove",
            # Common
            "ok": "OK",
            "cancel": "Cancel",
            "yes": "Yes",
            "no": "No",
            "error": "Error",
            "warning": "Warning",
        },
        "ar": {
            # Application
            "app_title": "Hrisa Docs",
            # Tabs (Right-to-left text)
            "tab_documents": "المستندات",
            "tab_themes": "المواضيع",
            "tab_synthesis": "التوليف",
            "tab_settings": "الإعدادات",
            # Menu
            "menu_file": "ملف",
            "menu_import": "استيراد",
            "menu_open_file": "فتح ملف",
            "menu_import_url": "استيراد من URL",
            "menu_exit": "خروج",
            "menu_project": "مشروع",
            "menu_new_project": "مشروع جديد",
            "menu_manage_projects": "إدارة المشاريع",
            "menu_project_settings": "إعدادات المشروع",
            "menu_settings": "الإعدادات",
            "menu_appearance": "المظهر",
            "menu_chunk_settings": "إعدادات التقطيع",
            "menu_model_settings": "إعدادات النموذج",
            "menu_help": "مساعدة",
            "menu_about": "حول",
            "appearance_restart_msg": "تم تحديث إعدادات المظهر. قد تتطلب بعض التغييرات إعادة تشغيل التطبيق للحصول على التأثير الكامل.",
            # Appearance settings dialog
            "dialog_appearance_settings": "إعدادات المظهر",
            "section_theme": "السمة",
            "section_size": "الحجم وإمكانية الوصول",
            "label_theme": "السمة",
            "label_size_profile": "ملف تعريف الحجم",
            "theme_dark": "داكن",
            "theme_light": "فاتح",
            "theme_dark_desc": "يقلل المظهر الداكن من إجهاد العين في البيئات منخفضة الإضاءة ويوفر البطارية على شاشات OLED.",
            "theme_light_desc": "يوفر المظهر الفاتح تباينًا عاليًا وهو مثالي للبيئات جيدة الإضاءة.",
            "size_small": "صغير (مضغوط)",
            "size_medium": "متوسط (مريح)",
            "size_large": "كبير (سهل الوصول)",
            "size_small_desc": "واجهة مضغوطة بخطوط وعناصر تحكم أصغر. يزيد من مساحة الشاشة.",
            "size_medium_desc": "واجهة متوازنة بأحجام مريحة. موصى به لمعظم المستخدمين.",
            "size_large_desc": "خطوط وعناصر تحكم أكبر لتحسين القراءة. مثالي لاحتياجات إمكانية الوصول أو الشاشات الكبيرة.",
            "size_info": "اختر ملف تعريف حجم أكبر لتحسين القراءة وإمكانية الوصول. يؤثر هذا على أحجام الخطوط وأبعاد الأزرار والتباعد في التطبيق بأكمله.",
            "appearance_info": "سيتم تطبيق التغييرات على الفور. قد تحتاج إلى إعادة تشغيل التطبيق حتى تصبح جميع التغييرات سارية المفعول.",
            "settings_applied": "تم تطبيق الإعدادات",
            "settings_applied_msg": "تم تطبيق إعدادات المظهر. قد تتطلب بعض التغييرات إعادة تشغيل التطبيق.",
            # Files tab
            "section_input_docs": "المستندات المصدر",
            "section_output_files": "الملفات المُنشأة",
            "status_no_output_files": "لا توجد ملفات منشأة",
            "status_n_output_files": "{} ملف منشأ",
            "btn_refresh": "تحديث",
            "btn_open": "فتح",
            "btn_open_folder": "فتح المجلد",
            "btn_delete": "حذف",
            "btn_delete_all": "حذف الكل",
            "btn_cancel": "إلغاء",
            "btn_duplicate": "تكرار",
            "tooltip_refresh_files": "تحديث قائمة الملفات",
            "tooltip_open_file": "فتح الملف المحدد",
            "tooltip_open_folder": "فتح مجلد الإخراج",
            "tooltip_delete_file": "حذف الملف المحدد",
            # Document tab
            "btn_add": "إضافة",
            "btn_remove": "إزالة",
            "btn_clear_all": "مسح الكل",
            "btn_clear_database": "إعادة تعيين",
            "btn_process": "معالجة المستندات",
            "status_no_docs": "لا توجد مستندات محملة",
            "status_n_docs": "{} مستند محمل",
            "status_processing": "جاري المعالجة...",
            "status_complete": "اكتملت المعالجة: {} قطعة",
            "status_processing_failed": "فشلت المعالجة",
            "status_ready_local": "جاهز - معالجة محلية 100% (بدون سحابة)",
            "status_added_docs": "تمت إضافة {} مستند",
            "status_discovering_themes": "جاري اكتشاف المواضيع...",
            "status_theme_discovery_failed": "فشل اكتشاف المواضيع",
            "status_generating_book": "جاري إنشاء الكتاب...",
            "status_synthesis_failed": "فشل إنشاء الكتاب",
            "status_writing_chapter": "كتابة الفصل {}/{}",
            "status_generating_outline": "...جاري إنشاء مخطط الفصل",
            "status_synthesizing_content": "...جاري توليف المحتوى",
            "status_formatting_output": "...جاري تنسيق الإخراج",
            # Worker progress messages
            "worker_initializing": "...جاري التهيئة",
            "worker_processing_doc": "...جاري معالجة {}",
            "worker_embedding_chunks": "...جاري دمج {} قطعة",
            "worker_embedding_chunk": "...جاري دمج القطعة {}/{}",
            "worker_completed_stored": "اكتمل! تم تخزين {} قطعة",
            "worker_retrieving_chunks": "...جاري استرجاع القطع",
            "worker_analyzing_chunks": "...جاري تحليل {} قطعة",
            "worker_clustering": "...جاري تجميع المواضيع",
            "worker_discovered_themes": "تم اكتشاف {} موضوع",
            "worker_loading_themes": "...جاري تحميل المواضيع",
            "worker_synthesizing_chapters": "...جاري توليف {} فصل",
            "worker_generating_markdown": "...جاري إنشاء Markdown",
            "worker_generating_docx": "...جاري إنشاء DOCX",
            "worker_generating_pdf": "...(جاري إنشاء PDF (قد يستغرق دقيقة",
            "worker_synthesis_complete": "!اكتمل التوليف",
            # Tooltips - Documents
            "tooltip_add_docs": "إضافة مستندات PDF",
            "tooltip_remove_doc": "إزالة المستند المحدد",
            "tooltip_clear_all": "إزالة جميع المستندات",
            "tooltip_clear_database": "إعادة تعيين قاعدة البيانات المتجهة بالكامل",
            "tooltip_process_docs": "استخراج النص وتقسيمه ودمج المستندات",
            "tooltip_discover_themes": "تحليل المستندات واكتشاف المواضيع",
            # Theme tab
            "btn_discover_themes": "اكتشاف المواضيع",
            "btn_rename": "إعادة تسمية",
            "btn_merge": "دمج",
            "btn_delete": "حذف",
            "label_discovered_themes": "المواضيع المكتشفة",
            "label_chunks": "قطع",
            "status_no_themes": "لم يتم اكتشاف مواضيع بعد",
            "status_n_themes": "{} موضوع مكتشف",
            "theme_discovery_complete": "اكتمل اكتشاف المواضيع: {} موضوع",
            # Tooltips - Themes
            "tooltip_rename_theme": "إعادة تسمية الموضوع المحدد",
            "tooltip_merge_themes": "دمج المواضيع المحددة",
            "tooltip_delete_theme": "حذف الموضوع المحدد",
            # Synthesis tab
            "label_synthesis_config": "تكوين التوليف",
            "label_theme_discovery": "اكتشاف المواضيع",
            "label_num_themes": ":عدد المواضيع",
            "label_auto_detect": "الكشف التلقائي عن العدد الأمثل",
            "label_synthesis_settings": "إعدادات التوليف",
            "label_synthesis_level": ":مستوى التوليف",
            "label_chunks_per_chapter": ":كثافة التوليف",
            "label_output_settings": "إعدادات الإخراج",
            "label_output_format": ":تنسيق الإخراج",
            "label_include_citations": "تضمين الاستشهادات المصدرية",
            "btn_start_synthesis": "🚀 بدء التوليف",
            "status_ready": "جاهز للتوليف",
            "status_configure": "قم بتكوين الإعدادات ومعالجة المستندات للبدء",
            "synthesis_complete": "!اكتمل التوليف",
            # Tooltips - Synthesis
            "tooltip_num_themes": "عدد المواضيع المراد اكتشافها",
            "tooltip_auto_detect": "تحديد العدد الأمثل للمواضيع تلقائيًا",
            "tooltip_synthesis_level": "طول الإخراج بالنسبة للمستندات المصدر",
            "tooltip_chunks_per_chapter": "يتحكم في كثافة التوليف: قطع أكثر = أكثر تفصيلاً، أقل = أكثر تكثيفًا (يوصى بـ 50-300)",
            "tooltip_output_format": "تنسيق الإخراج للكتاب الناتج (يتطلب PDF برنامج pandoc + MacTeX)",
            "tooltip_include_citations": "إضافة استشهادات للمستندات المصدر",
            "tooltip_start_synthesis": "بدء توليف الكتاب",
            # Settings tab
            "label_language": ":اللغة",
            "label_language_ui": ":لغة الواجهة",
            "label_language_pipeline": ":لغة خط الأنابيب",
            "label_ollama_model": ":نموذج Ollama",
            "label_vector_store": ":مخزن المتجهات",
            "label_output_dir": ":دليل الإخراج",
            # Synthesis levels
            "synthesis_short": "(15%) قصير",
            "synthesis_normal": "(30%) عادي",
            "synthesis_comprehensive": "(50%) شامل",
            # Output formats
            "format_markdown": "Markdown",
            "format_docx": "DOCX",
            "format_pdf": "PDF",
            "format_both": "Markdown + DOCX",
            "format_all": "(MD + DOCX + PDF) الكل",
            # Dialogs
            "dialog_select_pdfs": "اختر مستندات PDF",
            "dialog_pdf_filter": "(*.pdf) ملفات PDF",
            "dialog_no_documents": "لا توجد مستندات",
            "dialog_no_documents_msg": ".الرجاء إضافة بعض المستندات أولاً",
            "dialog_processing_complete": "اكتملت المعالجة",
            "dialog_processing_complete_msg": "!تمت معالجة المستندات بنجاح\n{} :إجمالي القطع",
            "dialog_can_discover_themes": ".يمكنك الآن اكتشاف المواضيع",
            "dialog_processing_error": "خطأ في المعالجة",
            "dialog_processing_error_msg": ":فشلت معالجة المستندات\n\n{}",
            "dialog_theme_discovery_complete": "اكتمل اكتشاف المواضيع",
            "dialog_theme_discovery_complete_msg": "!{} تم اكتشاف موضوع\n.يمكنك الآن مراجعة وتحرير المواضيع، ثم إنشاء كتابك",
            "dialog_theme_discovery_error": "خطأ في اكتشاف المواضيع",
            "dialog_theme_discovery_error_msg": ":فشل اكتشاف المواضيع\n\n{}",
            "dialog_no_themes": "لا توجد مواضيع",
            "dialog_no_themes_msg": ".الرجاء اكتشاف المواضيع أولاً قبل إنشاء الكتاب",
            "dialog_synthesis_complete": "اكتمل التوليف",
            "dialog_synthesis_success": "!تم إنشاء الكتاب بنجاح",
            "dialog_synthesis_error": "خطأ في التوليف",
            "dialog_synthesis_error_msg": ":فشل إنشاء الكتاب\n\n{}",
            "dialog_confirm_merge": "تأكيد الدمج",
            "dialog_confirm_merge_msg": ".تحذير: المواضيع لها أحجام مختلفة جداً\n\n:المواضيع المراد دمجها\n{}\n\n.أحد المواضيع أكبر بكثير من الآخر. هل أنت متأكد من دمجها؟",
            "dialog_rename_theme": "إعادة تسمية الموضوع",
            "dialog_rename_theme_msg": ":أدخل اسم الموضوع الجديد",
            "dialog_clear_database": "إعادة تعيين قاعدة البيانات",
            "dialog_clear_database_msg": "⚠️ تحذير: ستحذف هذه العملية جميع البيانات:\n\n• جميع قطع المستندات\n• جميع المواضيع المكتشفة\n• جميع التضمينات المتجهة\n\nهذه العملية لا رجعة فيها.\n\nهل تريد المتابعة؟",
            "dialog_database_cleared": "تمت إعادة تعيين قاعدة البيانات",
            "dialog_database_cleared_msg": ".تمت إعادة تعيين قاعدة البيانات بالكامل",
            "dialog_about_title": "حول معالج المستندات",
            "dialog_about_content": "<h2>معالج المستندات</h2><p>توليف المستندات القائم على RAG باستخدام نماذج لغوية محلية</p><p><b>:الميزات</b></p><ul><li>معالجة محلية 100% (خصوصية أولاً)</li><li>اكتشاف اللغة التلقائي</li><li>اكتشاف المواضيع عبر التجميع</li><li>(MD, DOCX, PDF) تصدير بتنسيقات متعددة</li></ul><p><b>:المكدس التقني</b> ChromaDB, Ollama, PyQt6</p>",
            # Project Dashboard
            "projects_dashboard": "لوحة معلومات المشاريع",
            "btn_new_project": "مشروع جديد",
            "btn_favorite": "مفضلة",
            "btn_unfavorite": "إزالة من المفضلة",
            "btn_archive": "أرشفة",
            "btn_delete_permanent": "حذف نهائي",
            "placeholder_search": "...بحث عن المشاريع",
            "placeholder_project_name": "أدخل اسم المشروع",
            "placeholder_description": "وصف اختياري",
            "filter_all": "كل المشاريع",
            "filter_active": "نشط",
            "filter_archived": "مؤرشف",
            "filter_favorites": "المفضلة",
            "sort_updated": "آخر تعديل",
            "sort_created": "تاريخ الإنشاء",
            "sort_opened": "آخر فتح",
            "sort_name": "الاسم",
            "label_name": "الاسم",
            "label_description": "الوصف",
            "label_template": "القالب",
            "label_mark_favorite": "وضع علامة كمفضل",
            "template_default": "افتراضي",
            "template_academic": "بحث أكاديمي",
            "template_legal": "تحليل قانوني",
            "template_creative": "كتابة إبداعية",
            "template_technical": "وثائق تقنية",
            "dialog_new_project": "مشروع جديد",
            "dialog_delete_project": "حذف المشروع",
            "msg_project_name_required": "اسم المشروع مطلوب",
            "msg_project_created": "!تم إنشاء المشروع بنجاح",
            "msg_create_project_error": "خطأ في إنشاء المشروع",
            "msg_delete_archived_project": "حذف هذا المشروع المؤرشف نهائياً؟",
            "msg_delete_active_project": "أرشفة أو حذف هذا المشروع نهائياً؟",
            "msg_project_deleted": "تم حذف المشروع نهائياً",
            "msg_project_archived": "تم أرشفة المشروع",
            "success": "نجاح",
            # Project Switcher (Main Window)
            "current_project": "المشروع الحالي",
            "no_project": "لا يوجد مشروع",
            "btn_manage_projects": "إدارة المشاريع",
            "btn_project_settings": "إعدادات المشروع",
            "msg_project_load_error": "فشل تحميل المشروع",
            "msg_coming_soon": "!قريباً",
            "info": "معلومات",
            # Project Settings Dialog
            "dialog_project_settings": "إعدادات المشروع",
            "section_project_info": "معلومات المشروع",
            "section_llm_settings": "إعدادات نموذج اللغة",
            "section_processing_settings": "إعدادات المعالجة",
            "section_output_settings": "إعدادات الإخراج",
            "label_project_name": "اسم المشروع",
            "label_author": "المؤلف",
            "label_tags": "العلامات",
            "placeholder_tags": "علامات مفصولة بفواصل",
            "label_language": "اللغة",
            "label_llm_model": "نموذج LLM",
            "label_temperature": "درجة الحرارة",
            "label_embedding_model": "نموذج التضمين",
            "label_chunk_size": "حجم الجزء",
            "label_chunk_overlap": "تداخل الأجزاء",
            "label_output_format": "تنسيق الإخراج الافتراضي",
            "label_include_citations": "تضمين الاقتباسات",
            "label_citation_style": "نمط الاقتباس",
            "msg_settings_saved": "تم حفظ إعدادات المشروع بنجاح",
            # Common
            "ok": "موافق",
            "cancel": "إلغاء",
            "yes": "نعم",
            "no": "لا",
            "error": "خطأ",
            "warning": "تحذير",
        },
    }

    def __init__(self, language: Language = Language.FRENCH):
        """
        Initialize language manager.

        Args:
            language: Default language (French)
        """
        self.current_language = language
        self._translations = self.TRANSLATIONS[language.value]

    def set_language(self, language: Language):
        """Set the current language."""
        self.current_language = language
        self._translations = self.TRANSLATIONS[language.value]

    def get(self, key: str, *args) -> str:
        """
        Get translated text for a key.

        Args:
            key: Translation key
            *args: Format arguments

        Returns:
            Translated and formatted text
        """
        text = self._translations.get(key, key)
        if args:
            text = text.format(*args)
        return text

    def get_language_name(self, lang: Language) -> str:
        """Get display name for a language."""
        names = {
            Language.FRENCH: "Français",
            Language.ENGLISH: "English",
            Language.ARABIC: "العربية",
        }
        return names.get(lang, lang.value)

    def get_language_code(self) -> str:
        """Get current language code (fr, en, ar)."""
        return self.current_language.value

    @classmethod
    def get_available_languages(cls) -> list[Language]:
        """Get list of available languages."""
        return [Language.FRENCH, Language.ENGLISH, Language.ARABIC]


# Global instance
_language_manager = None


def get_language_manager() -> LanguageManager:
    """Get global language manager instance."""
    global _language_manager
    if _language_manager is None:
        _language_manager = LanguageManager()
    return _language_manager


def set_global_language(language: Language):
    """Set global language."""
    get_language_manager().set_language(language)
